name: eve-kernel build
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - "eve-kernel-amd64-v6.1.38-generic"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  packages:
    runs-on: self-hosted
    steps:
      - name: Get eve-kernel
        uses: actions/checkout@v3
        with:
          ref: "eve-kernel-amd64-v6.1.38-generic"
      - name: Always build eve-kernel-amd64
        run: |
          make -f Makefile.eve BRANCH?=${GITHUB_REF##*/} kernel-gcc
      - name: Log in to Docker Hub
        if: ( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) || github.event_name == 'push'  # Only if PR is merged or it was direct push
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
      - name: Login to DockerHUB
        if: ( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) || github.event_name == 'push'  # Only if PR is merged or it was direct push
        run: |
          echo "${{ secrets.RELEASE_DOCKERHUB_TOKEN }}" |\
             docker login -u "${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}" --password-stdin
      - name: Push eve-kernel-amd64-v6.1.38-generic if PR approved or pushed
        if: ( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) || github.event_name == 'push'  # Only if PR is merged or it was direct push
        run: |
          make -f Makefile.eve BRANCH?=${GITHUB_REF##*/} push-gcc
