---
name: eve-kernel build
on:  # yamllint disable-line rule:truthy
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - "eve-kernel-amd64-v6.1.38-generic"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  packages:
    runs-on: self-hosted
    if: github.event.review.state == 'approved'
    steps:
      - name: Get eve-kernel
        uses: actions/checkout@v3
        with:
          ref: "eve-kernel-amd64-v6.1.38-generic"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
      - name: Login to DockerHUB
        run: |
          echo "${{ secrets.RELEASE_DOCKERHUB_TOKEN }}" |\
             docker login -u "${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}" --password-stdin
      - name: Build eve-kernel-amd64-v6.1.38-generic
        run: |
          make -f Makefile.eve BRANCH?=${GITHUB_REF##*/} push-gcc
